// Monochrome brand — primary flips with the theme so it always reads as
// the inverse of the surface (white on dark, black on light). Mirrors the
// landing page's `.btn-vibe` which is a solid white CTA in dark mode.
export const staticPrimaryColor = "#000000"
export const staticPrimaryDarkenColor = "#1a1a1a"
export const accentColor = "#EC4899"

export const themes = {
    light: {
        dark: false,
        colors: {
            primary: "#000000",
            "on-primary": "#ffffff",
            "primary-darken-1": "#1a1a1a",
            secondary: accentColor,
            "on-secondary": "#fff",
            "secondary-darken-1": "#DB2777",
            accent: accentColor,
            "on-accent": "#fff",
            success: "#10B981",
            "on-success": "#fff",
            "success-darken-1": "#059669",
            info: "#06B6D4",
            "on-info": "#fff",
            "info-darken-1": "#0891B2",
            warning: "#F59E0B",
            "on-warning": "#fff",
            "warning-darken-1": "#D97706",
            error: "#EF4444",
            "on-error": "#fff",
            "error-darken-1": "#DC2626",
            background: "#FCFCFD",
            "on-background": "#0F0A1F",
            surface: "#FFFFFF",
            "on-surface": "#0F0A1F",
            "grey-50": "#FAFAFA",
            "grey-100": "#F4F4F5",
            "grey-200": "#E4E4E7",
            "grey-300": "#D4D4D8",
            "grey-400": "#A1A1AA",
            "grey-500": "#71717A",
            "grey-600": "#52525B",
            "grey-700": "#3F3F46",
            "grey-800": "#27272A",
            "grey-900": "#18181B",
            "grey-light": "#F4F4F5",
            "perfect-scrollbar-thumb": "#D4D4D8",
            "skin-bordered-background": "#FFFFFF",
            "skin-bordered-surface": "#FFFFFF",
            "expansion-panel-text-custom-bg": "#F4F4F5",
        },
        variables: {
            "code-color": "#000000",
            "overlay-scrim-background": "#1B1340",
            "tooltip-background": "#1B1340",
            "overlay-scrim-opacity": 0.5,
            "hover-opacity": 0.06,
            "focus-opacity": 0.1,
            "selected-opacity": 0.08,
            "activated-opacity": 0.16,
            "pressed-opacity": 0.14,
            "dragged-opacity": 0.1,
            "disabled-opacity": 0.6,
            "border-color": "#0F0A1F",
            "border-opacity": 0.12,
            "table-header-color": "#F4F4F5",
            "high-emphasis-opacity": 0.95,
            "medium-emphasis-opacity": 0.7,
            "switch-opacity": 0.2,
            "switch-disabled-track-opacity": 0.3,
            "switch-disabled-thumb-opacity": 0.4,
            "switch-checked-disabled-opacity": 0.3,
            "track-bg": "#F1F0F2",
            "shadow-key-umbra-color": "#1B1340",
            "shadow-xs-opacity": 0.1,
            "shadow-sm-opacity": 0.12,
            "shadow-md-opacity": 0.14,
            "shadow-lg-opacity": 0.16,
            "shadow-xl-opacity": 0.18,
        },
    },
    dark: {
        dark: true,
        colors: {
            primary: "#ffffff",
            "on-primary": "#000000",
            "primary-darken-1": "#e5e5e5",
            secondary: accentColor,
            "on-secondary": "#fff",
            "secondary-darken-1": "#DB2777",
            accent: accentColor,
            "on-accent": "#fff",
            success: "#10B981",
            "on-success": "#fff",
            "success-darken-1": "#059669",
            info: "#06B6D4",
            "on-info": "#fff",
            "info-darken-1": "#0891B2",
            warning: "#F59E0B",
            "on-warning": "#fff",
            "warning-darken-1": "#D97706",
            error: "#EF4444",
            "on-error": "#fff",
            "error-darken-1": "#DC2626",
            background: "#000000",
            "on-background": "#f0f0f0",
            surface: "#1d1f23",
            "on-surface": "#f0f0f0",
            "grey-50": "#080808",
            "grey-100": "#111111",
            "grey-200": "#1a1a1a",
            "grey-300": "#222222",
            "grey-400": "#333333",
            "grey-500": "#555555",
            "grey-600": "#888888",
            "grey-700": "#bbbbbb",
            "grey-800": "#dddddd",
            "grey-900": "#f0f0f0",
            "grey-light": "#111111",
            "perfect-scrollbar-thumb": "#333333",
            "skin-bordered-background": "#000000",
            "skin-bordered-surface": "#1d1f23",
        },
        variables: {
            "code-color": "#ffffff",
            "overlay-scrim-background": "#000000",
            "tooltip-background": "#1a1a1a",
            "overlay-scrim-opacity": 0.7,
            "hover-opacity": 0.08,
            "focus-opacity": 0.12,
            "selected-opacity": 0.1,
            "activated-opacity": 0.18,
            "pressed-opacity": 0.16,
            "dragged-opacity": 0.12,
            "disabled-opacity": 0.5,
            "border-color": "#ffffff",
            "border-opacity": 0.18,
            "table-header-color": "#111111",
            "high-emphasis-opacity": 0.95,
            "medium-emphasis-opacity": 0.7,
            "switch-opacity": 0.4,
            "switch-disabled-track-opacity": 0.4,
            "switch-disabled-thumb-opacity": 0.8,
            "switch-checked-disabled-opacity": 0.3,
            "track-bg": "#1a1a1a",
            "shadow-key-umbra-color": "#000000",
            "shadow-xs-opacity": 0.4,
            "shadow-sm-opacity": 0.5,
            "shadow-md-opacity": 0.55,
            "shadow-lg-opacity": 0.6,
            "shadow-xl-opacity": 0.65,
        },
    },
}
export default themes
